### ISSUE TITLE
Color issues with the latest release

### ISSUE THREAD

**Issue by stesvis** [hicknhack-software/semantic-colorizer#23]
After the latest update (1.3.1) some of my color codes don't apply anymore.

In particular:

- **public** keyword on properties: I set it to be bold and orange
![image](https://user-images.githubusercontent.com/6062684/40127571-e93ca410-58ec-11e8-93e9-66be204c42eb.png)
- **Fields**: `_guide` should be green, but another color applies. It's the same I used for types (see screenshot above)
- **Methods**: I set the to a type of yellow (same as the constructors), but it's showing the same color as types:
![image](https://user-images.githubusercontent.com/6062684/40127864-9891a154-58ed-11e8-873f-2071ec79bca3.png)
- **out** keyword: same problem as public keyword in properties:
![image](https://user-images.githubusercontent.com/6062684/40128056-f7708fb4-58ed-11e8-8468-e45c0f36f422.png)
- **Properties**: that is not the  color i set for properties (should be the same purple)
![image](https://user-images.githubusercontent.com/6062684/40128189-4184df9c-58ee-11e8-9d81-a0cad6ffbc7d.png)

Would it be possible to roll back to the previous version while you investigate?
This is an older screenshot i still had, to show how it's supposed to be:
![image](https://user-images.githubusercontent.com/6062684/40128636-5695c9d6-58ef-11e8-9f42-5dcff459a729.png)

It's an incredibly valuable tool that makes works so much better, I realize it now that a few colors i was used to are gone :)

**Comment by arBmind** [comment]
Thank you for the effort to document the bugs. I will investigate these as soon as possible.

**Comment by stesvis** [comment]
Thank you.
Today after updating VS2017 to v15.7.1 I saw that some colors came back.

Methods are yellow again, and fields are green.

**Comment by joshjje** [comment]
I have the same issue and there is no VS update to fix it.  Using VS2015 Update 3 latest.

**Comment by Lunar2kPS** [comment]
Minor related issue on my end as well. I just updated my Visual Studio today, which somehow fixed a lot of the syntax coloring problems I was having!

But one thing that hasn't been fixed is that the access modifiers (public, protected, etc.), and the abstract keyword on my C# properties are accidentally being colored with the property color (green in the picture below), when I'd like it to be the default color (below the properties in the picture below, just like the methods have not changed public and protected from its default blue color). 

![image](https://user-images.githubusercontent.com/25470751/40591762-fb57fac2-61e4-11e8-8bdb-c4c8fa1c5b85.png)

And P.S. - thank you so much for working on this syntax highlighting tool!! I was using one for a few years until they made it only available for people who pay yearly for it... But this one is fabulous and doesn't lag my C# editor! :)

**Comment by JackDMF** [comment]
I have the exact same problem as @2kCarlos and would love to see that bug fixed, and if someone pointed in the right direction I might even be able to help solving it. At least I would be willing to do so, because this extension is great! Thank you!

**Comment by emperador-ming** [comment]
Same problems here. I had to uninstall the extension. It's a pity because I really really love it.

**Comment by stesvis** [comment]
@arBmind would it be possible to roll back for now?
From VS it's not possible to install a previous version of an extension like we can do for packages.

**Comment by arBmind** [comment]
@stesvis Sorry for the inconvenience. I had no time to look into this.
Right now I am not even using C# and it's hard to find time for this.

I noticed the keyword glitch while fixing the VS2017 15.7 issues. But I could not find a key to distinguish them from the name. Has anybody an idea?

**Comment by arBmind** [comment]
should be fixed

**Comment by text-dev** [comment]
Highlighting is still broken in VS 2015.

**Comment by stesvis** [comment]
@arBmind thank you very much. so much appreciated

**Comment by joshjje** [comment]
@arBmind Yeah, also using VS 2015 and field highlighting (at least) is still broken :(

**Comment by arBmind** [comment]
@joshjje please create a new issue and describe what is wrong, so I can investigate.
